### ISSUE TITLE
Create Company Entity

### ISSUE THREAD

**Issue by LeonelSantiago** [wilsonrc/JobsScraper-Backend#1]
- Id `int`
- Name `string`
- Address `string`
- Country `string`
- Region `string`
- AllowsRemote `bool`

**Comment by vyzaldysanchez** [comment]
I already created this model in the `components/db-models` branch, I'm just waiting for https://github.com/wilsonrc/JobsScraper-Backend/pull/4 to get merged since I branched off from there.

**Comment by vyzaldysanchez** [comment]
Clossing issue since models branched got already merged.

**Comment by LeonelSantiago** [comment]
Great!
