### ISSUE TITLE
Create JobPost Entity

### ISSUE THREAD

**Issue by LeonelSantiago** [wilsonrc/JobsScraper-Backend#2]
**Properties:**
- Id `int`
- Title `string`
- Description `string`
- CompanyId `int` -> Foreing key from Company Entity
- HowToApply `string`
- IsRemote `bool`
- Location `string, Nullable`
- PostedAt `Datetime`

**Comment by vyzaldysanchez** [comment]
I already created this model in the `components/db-models` branch, I'm just waiting for https://github.com/wilsonrc/JobsScraper-Backend/pull/4 to get merged since I branched off from there.

**Comment by vyzaldysanchez** [comment]
Clossing issue since models branched got already merged.

**Comment by LeonelSantiago** [comment]
Great!
