### ISSUE TITLE
Implement typescript for development

### ISSUE THREAD

**Issue by vyzaldysanchez** [wilsonrc/JobsScraper-Backend#9]
We need to enable intellisense in the different editors/IDEs that we are going to use to built this tool, also, it will be cool to have some of the features that comes out-of-the-box with TypeScript.

**Comment by LeonelSantiago** [comment]
Do you have any VS extension in mind for it?

**Comment by vyzaldysanchez** [comment]
It comes out of the box normally, but you can install TSLint and TypeScript Hero.

**Comment by LeonelSantiago** [comment]
Great, thanks.
